version: '3.7'
services:
    thread-service:
        # network_mode: host
        container_name: 'thread_service'
        restart: always
        env_file:
            #     - ./.env.production
            - ./environment/.env
        build: .
        image: thread_service
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '4007:4007'
            - '50055:50055'
